name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Verify project structure
        run: |
          echo "=== Структура проекта ==="
          ls -la
          echo "=== Содержимое app/ ==="
          ls -la app/
          echo "=== Содержимое app/src/ ==="
          ls -la app/src/
      
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew clean assembleDebug --stacktrace --info
          echo "=== Поиск APK ==="
          find . -name "*.apk" || echo "APK не найден"
      
      - name: Check build outputs
        if: always()
        run: |
          echo "=== Содержимое build/ ==="
          ls -R app/build/ || echo "Папка build не существует"
