name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'
      
      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew clean assembleDebug --stacktrace
          echo "=== Поиск APK файлов ==="
          find . -name "*.apk" -type f | xargs ls -la
          echo "=== Содержимое папки outputs ==="
          ls -R app/build/outputs/
      
      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: chain-alarm
          path: |
            app/build/outputs/**/*.apk
            app/build/outputs/**/*.json
          if-no-files-found: error
